const { chromium, expect } = require('../encryption-visualizer/node_modules/@playwright/test');
const fs = require('node:fs');
let browser;
(async () => {
  browser = await chromium.launch({ channel: 'chrome' });
  const context = await browser.newContext({ viewport: { width: 390, height: 900 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.getByRole('radio', { name: 'Light mode' }).click();
  await page.reload();
  await expect(page.getByRole('radio', { name: 'Light mode' })).toHaveAttribute('aria-checked', 'true');
  await page.waitForFunction(() => !!navigator.serviceWorker.controller, { timeout: 20000 });
  const worker = await page.evaluate(() => navigator.serviceWorker.controller.scriptURL);
  await context.setOffline(true);
  await page.goto('http://127.0.0.1:4173/aes');
  await expect(page.getByRole('heading', { name: 'AES Encryption Visualizer', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Start Encryption Visualization', exact: true }).click();
  const pause = page.getByRole('button', { name: /^Pause(?: visualization)?$/ });
  if (await pause.count()) await pause.click();
  await page.getByRole('heading', { name: 'AES Encryption Visualizer', exact: true }).click();
  await page.keyboard.press('End');
  await expect(page.getByRole('button', { name: /^(?:Go to )?Next step$/i })).toBeDisabled();
  await expect(page.getByRole('heading', { name: 'Something went wrong', exact: true })).toHaveCount(0);
  await page.screenshot({ path: __dirname + '/evidence/production-offline-aes-mobile.png', fullPage: true });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'AES Encryption Visualizer', exact: true })).toBeVisible();
  await expect(page.getByText('No visualization data available', { exact: true })).toBeVisible();
  await context.setOffline(false);
  fs.writeFileSync(__dirname + '/evidence/production-smoke.json', JSON.stringify({ origin: 'http://127.0.0.1:4173', worker, themeReload: 'passed', offlineNavigation: 'passed', offlineAES: 'passed', offlineReload: 'passed', errors }, null, 2));
  if (errors.length) throw new Error(errors.join('\n'));
  await browser.close();
})().catch(async e => { console.error(e); if (browser) await browser.close(); process.exitCode = 1; });
